name: Deploy to Remote Server

on:
  push:
    branches:
      - main  # Replace with your desired branch

jobs:
  deploy:
    runs-on: ubuntu-22.04.03

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$AWS_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 655 ~/.ssh/id_rsa
          ssh-keyscan -H 51.20.78.69 >> ~/.ssh/known_hosts  # Replace <REMOTE_HOST> with the actual host
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy to Remote Server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@51.20.78.69 'bash -s' < deploy-script.sh  # Replace with actual remote user, host, and script path
