- name: executing remote ssh commands using ssh key
  uses: appleboy/ssh-action@v1.0.0
  with:
    host: 51.20.78.69
    username: ubuntu
    key: ${{ AWS_SSH_PRIVATE_KEY }}
    port: 22
    script: /home/ubuntu/deploy-script.sh
