name: Deploy to AWS EC2

on:
  push:
    branches:
      - main # Change this to your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Initialize SSH agent
        run: eval $(ssh-agent -s)
      - name: Add SSH key to agent
        run: ssh-add ~/.ssh/id_rsa
      - name: Create SSH directory
        run: |
          mkdir -p ~/.ssh
          chmod 777 ~/.ssh
          echo "$AWS_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 777 ~/.ssh/id_rsa
          ssh-keyscan -H 51.20.78.69 >> ~/.ssh/known_hosts

      - name: Run deployment script
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@51.20.78.69 '/home/ubuntu/deploy-script.sh'
